#!/bin/bash
nvidia-settings -a CurrentMetaMode="DP-0: 1920x1080_144 @1440x1080 +0+0 {ViewPortIn=1440x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_144 @1920x1080 +1440+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
