#!/bin/bash
current_sink=$(pactl info | grep "Default Sink" | cut -d ' ' -f3)

if [ "$current_sink" == "alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo" ]; then
    pactl set-default-sink alsa_output.pci-0000_0b_00.4.analog-stereo
elif [ "$current_sink" == "alsa_output.pci-0000_0b_00.4.analog-stereo" ]; then
    pactl set-default-sink alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo
else
    echo "The current default sink is neither alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo nor alsa_output.pci-0000_0b_00.4.analog-stereo."
fi
